### ISSUE TITLE
sql seed has users and things commented out

### ISSUE THREAD

**Issue by TimNZ** [manjeshpv/node-oauth2-server-implementation#16]
components/oauth/seed.js

Is there a reason for this?

**Comment by manjeshpv** [comment]
Automatically seed is enabled, If tables not found in db then seed code will execute.

**Comment by TimNZ** [comment]
Sorry perhaps I was not clear.

Why are users and things table code commented out in seed.js?

https://github.com/manjeshpv/node-oauth2-server-implementation/blob/master/components/oauth/seed.js#L20

I set config.js to use 'sql', and 'sqlite' for db provider, and on app run Sequelize threw an error on init.

Uncommenting the code in seed.js fixes this.
