### ISSUE TITLE
user is undefined

### ISSUE THREAD

**Issue by nivek-ph** [manjeshpv/node-oauth2-server-implementation#26]
https://github.com/manjeshpv/node-oauth2-server-implementation/blob/5dc36da4a093bf3c0f4d5a10027df822850a642d/components/oauth/models.js#L241

**Comment by FrozenCaptain** [comment]
The fix in issue #19 results in a missing parameter `scope` in `function validateScope()`. The function will always return false. Results in a 503. 

Remove the current line with `return true` **Temporarily**

**Comment by nivek-ph** [comment]
thanks a lot.
